name: Generate CODEOWNERS

on:
  push:
    branches: [main]

jobs:
  generate-codeowners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate CODEOWNERS file
        run: |
          echo "${{ secrets.CODEOWNERS_SECRET }}" > .github/CODEOWNERS
